### ISSUE TITLE
[Feature Request] Area for Project Description 

### ISSUE THREAD

**Issue by michael-spengler** [CommunityXYZ/website#14]
I propose to introduce a textarea where community creators can describe their community. 

If I e.g. had never heard of verto I would not find any link to https://verto.exchange/ from this place: https://community.xyz/#usjm4PCxUd5mtaon7zc97-dt-3qf67yPyqgzLnLqk5A

**Comment by cedriking** [comment]
Hello @michael-spengler , a community member was already working on this. It's in this PR https://github.com/CommunityXYZ/website/pull/11 . It has already been approved. You are now able to start setting those, the frontend of it is being built now 👍
