### ISSUE TITLE
Loading communities is slow.

### ISSUE THREAD

**Issue by trusktr** [CommunityXYZ/website#16]
Will it ever be fast? Can it be paginated, or something? Or is that a limitation of blockchain tech?

**Comment by cedriking** [comment]
Hello @trusktr is this something happening on a particular Community? Or a specific page? Also, is this happening on the permaweb version? Which one? Or it's on community.xyz? The website loads quite fast since we implemented the basic caching system a few weeks back.

**Comment by cedriking** [comment]
No updates in a week. Closing issue.

**Comment by trusktr** [comment]
This page take really long to load all the communities: https://community.xyz/communities

**Comment by cedriking** [comment]
Hello @trusktr , the page can be improved (and will be improved) with two options:
1. As you mentioned, it can be paginated, but it wont be able to be sorted like it's now, by the total amount of members + opportunities they have. Which means the most active on top.
2. Having a cache that shows a recent state, but not the latest one. This is the best option and the one that we will be using soon.
