### ISSUE TITLE
Improve Usability --> for first time users

### ISSUE THREAD

**Issue by michael-spengler** [CommunityXYZ/website#6]
I'd like to share 10 % of my PST related to https://community.xyz/#vyDjA2UggLj12tcFR-lKAo1kKaZyNeAM2twEJ62xkco/tokens with a contributor.

Trying this I got stuck at the following screen.
![Screen Shot 2020-09-19 at 2 04 17 PM](https://user-images.githubusercontent.com/43786652/93666797-409d5780-fa81-11ea-9c8d-675bd7aaa732.png)

I guess "Recipient" could have a placeholder "Enter the recipient's Arweave wallet address..."

Am I right? If yes let me try to implement it and create a PR - hints are welcome.

**Comment by cedriking** [comment]
Thanks a lot Michael, PR's are greatly apreciated. 
Using a placeholder doesn't fit with the current UX and structure of the website, it will need to be a `small` tag just like how this one is done: 
![image](https://user-images.githubusercontent.com/33100863/94074865-b413d180-fdbf-11ea-97f1-983b882dc8b1.png)

Before approving the PR, it will need to be changed to this format. I also noticed that you used the ` quote for the placeholder. On Pug, the standard is to use a double quote `"`, if ever needed, please use double quotes for attribute values.

Thanks again for your PR! 👍
